// File generated by FlutterFire CLI.
// This is a placeholder - you'll need to run `flutterfire configure` to generate the actual file
// For now, this provides the structure

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // TODO: Replace with your actual Firebase configuration
  // Run: flutter pub global activate flutterfire_cli

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcqn0HCH1T2U8bbWr1qOi3AL8llqtP2nA',
    appId: '1:871275592843:android:1446d9d2e95c3d37c9288e',
    messagingSenderId: '871275592843',
    projectId: 'x-pire-2e0c5',
    databaseURL: 'https://x-pire-2e0c5-default-rtdb.firebaseio.com',
    storageBucket: 'x-pire-2e0c5.firebasestorage.app',
  );

  // Then: flutterfire configure

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn6EaTwkCMyQjbMY6Gf1LnA-V_T-fTrj0',
    appId: '1:871275592843:ios:d178a4d208ffcf33c9288e',
    messagingSenderId: '871275592843',
    projectId: 'x-pire-2e0c5',
    databaseURL: 'https://x-pire-2e0c5-default-rtdb.firebaseio.com',
    storageBucket: 'x-pire-2e0c5.firebasestorage.app',
    iosBundleId: 'com.example.xPire',
  );

}